<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="domain\Models.fs" />
    <Compile Include="Persistence\Dapper.fs" />
    <Compile Include="Persistence\DbInitialization.fs" />
    <Compile Include="Persistence\SessionRepository.fs" />
    <Compile Include="Persistence\UserRepository.fs" />
    <Compile Include="Services\AuthService.fs" />
<!--    <Compile Include="services\AuthService.fs" />-->
<!--    <Folder Include="API\" />-->
    <Compile Include="API\EndUserEndpoints.fs" />
    <Compile Include="API\RegisterEndpoint.fs" />
    <Compile Include="Update.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

<!--  <ItemGroup>-->
<!--    <Compile Include="domain\Models.fs" />-->
<!--  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Fabulous" Version="2.4.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
  </ItemGroup>

</Project>
